---
openapi: 3.0.3
info:
  title: peanuts-api API
  version: 1.0-SNAPSHOT
paths:
  /users:
    get:
      tags:
        - Users Resource
      parameters:
        - name: first
          in: query
          schema:
            format: int32
            default: 0
            type: integer
        - name: max
          in: query
          schema:
            format: int32
            default: 20
            type: integer
        - name: search
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/count:
    get:
      tags:
        - Users Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                format: int32
                type: integer
  /users/{id}:
    get:
      tags:
        - Users Resource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}/credentials:
    get:
      tags:
        - User Resource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CredentialData'
    put:
      tags:
        - Peanuts Resource
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CredentialData'
      responses:
        "204":
          description: No Content
components:
  schemas:
    CredentialData:
      type: object
      properties:
        value:
          type: string
          example: /bVkHA4G/VOskjaCgNYyTz1BhgD+9X8bxCNEPGGpnDCJbWHDXIW0G8IlSBhDdJsXTjrXt/7yQguBwJ3sxSmSKA==
        salt:
          type: string
          example: lZtleWv1DeEcNIr8MTzdeg==
        algorithm:
          type: string
          example: pbkdf2-sha256
        iterations:
          format: int32
          type: integer
          example: 27500
        type:
          type: string
          example: password
    User:
      type: object
      properties:
        username:
          type: string
          example: charlie
        firstName:
          type: string
          example: Charlie
        lastName:
          type: string
          example: Brown
        email:
          type: string
          example: charlie.brown@peanuts.com
        birthday:
          type: string
          example: 1948-05-30
        gender:
          type: string
          example: male
        groups:
          type: array
          items:
            type: string
            example: peanuts
        roles:
          type: array
          items:
            type: string
            example: child