version: '3'
services:

  keycloak:
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 8080:8080
      - 8443:8443

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://192.168.56.10:5432/aatariak-keycloak
      KC_DB_USERNAME: farid
      KC_DB_PASSWORD: password
      KC_HOSTNAME: 192.168.56.10
      KEYCLOAK_LOGLEVEL: DEBUG

    volumes:
      - ./conf/quarkus.properties:/opt/keycloak/conf/quarkus.properties

    command: start-dev


